develop:
  build: .
  ports:
    - "8000:5000"
  env_file:
    - .env
  environment:
    ENVIRONMENT: dev
    DEBUG: "True"
  volumes:
    - ./python_app:/opt/flask_app/python_app/
  command: develop
  restart: always
